
services:
  db:
    image: qdrant/qdrant
    container_name: qdrant_db
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_data:/qdrant/storage

  agent-tools-mcp:
    build: ./agent-tools-mcp
    container_name: agent_tools_mcp
    ports:
      - "8000:8000"
    environment:
      - BRAVE_SEARCH_API_KEY=${BRAVE_SEARCH_API_KEY}
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8000
      - LOG_LEVEL=info
    volumes:
      - ./agent-tools-mcp/agent_tools_mcp:/app/agent_tools_mcp
      - ./agent-tools-mcp/tests:/app/tests
    depends_on:
      - db
